sudo: required
services:
  - docker
before_install:
  - docker build -t dcastrodale/docker-react-test -f Dockerfile.dev .
script:
  - docker run dcastrodale/docker-react-test npm run test -- --coverage